# ****🟢 LEVEL 1: Basics****

In [1]:
import numpy as np

**Question-01 : Create a NumPy array from a Python list [1,2,3,4,5]**

In [2]:
arr = np.array([1,2,3,4,5])

**Question-02 : Create a 2D array (2×3 matrix)**

In [3]:
arr2 = np.array([[1,2,3],[4,5,6]])

**Question-03 : Create an array of all zeros (3×3)**

In [4]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**Question-04 : Create an array of all ones (4×2)**

In [5]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

**Question-05 : Create an identity matrix of size 5**

In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**Question-06 : Generate numbers from 10 to 50 using arange()**

In [7]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**Question-07 : Create 10 evenly spaced numbers between 0 and 1**

In [8]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**Question-08 : Check the shape of an array**

In [9]:
arr.shape

(5,)

**Question-09 : Find number of dimensions of an array**

In [10]:
arr.ndim

1

**Question-10 : Find total elements in an array**

In [11]:
arr.size

5

**Question-11 : Check datatype of elements**

In [12]:
arr.dtype

dtype('int64')

**Question-12 : Convert a list of floats into integers**

In [13]:
arr.astype(int)

array([1, 2, 3, 4, 5])

**Question-13 : Create a 3×3 matrix with values from 1 to 9**

In [14]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Question-14 : Reshape a 1D array of 12 elements into 3×4**

In [15]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**Question-15 : Flatten a 2D array into 1D**

In [16]:
arr2.flatten()

array([1, 2, 3, 4, 5, 6])

**Question-16 : Create a copy vs view of an array**

In [17]:
copy = arr.copy()
view = arr.view()

**Question-17 : Replace all elements in array with 0**

In [18]:
arr[:] = 0

**Question-18 : Create array with random integers (1–100)**

In [19]:
np.random.randint(1,101,10)

array([18, 98, 40, 37, 79, 81, 72, 73, 46, 12])

**Question-19 : Generate random float numbers**

In [20]:
np.random.rand(5)

array([0.33919512, 0.65095615, 0.91568129, 0.2314357 , 0.69695622])

**Question-20 : Create an array filled with a specific number (e.g., 7)**

In [21]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

**Question-21 : Reverse an array**

In [22]:
arr[::-1]

array([0, 0, 0, 0, 0])

**Question-22 : Sort an array**

In [23]:
np.sort(arr)

array([0, 0, 0, 0, 0])

**Question-23 : Find min and max**

In [24]:
arr.min(), arr.max()

(np.int64(0), np.int64(0))

**Question-24 : Find index of max value**

In [25]:
np.argmax(arr)

np.int64(0)

**Question-25 : Check if array contains a specific value**

In [26]:
5 in arr

False